spring.application.name=sistema
spring.datasource.url=jdbc:mysql://localhost:3306/biblioteca_libros
spring.datasource.username=root
spring.datasource.password=
# CONFIGURACION DE SPRING CON MYSQL
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect